export const INCREMENT_COUNT = 'INCREMENT_COUNT'; //Test


export enum RepositoryActionType {
  SEARCH_REPOSITORIES         = 'SEARCH_REPOSITORIES',
  SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS',
  SEARCH_REPOSITORIES_ERROR   = 'SEARCH_REPOSITORIES_ERROR'
}
